[theme]
base = "light"
primaryColor = "#917952"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F2EE"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "error"
messageFormat = "%(asctime)s - %(levelname)s - %(message)s"

[server]
headless = true
runOnSave = false
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = true

[ui]
hideTopBar = false
hideSidebarNav = false
